### PR TITLE
Adjustments to support Angular 10 (backwards compat with 9)

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-angular-10-support)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
