### PR TITLE
Add bottom box shadow (elevation 3) for when a viewkeeper is active in modern theme

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-viewkeeper-modern-shadow](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-viewkeeper-modern-shadow)

**Comment by Blackbaud-TrevorBurch** [comment]
JFYI - because viewkeeper uses purely javascript to add styles we have to duplicate the `sky-elevation-3` style here and also make the `-1px` tweak in order to only apply the shadow to the bottom only.

**Review by Blackbaud-AlexKingman — DISMISSED** [review]
Looks ok from an engineering perspective.

**Comment by Blackbaud-AdamFunderburk** [comment]
Looking good on the elevation. Can anyone remind me why we add translucency to the container as well?

**Review by Blackbaud-AdamFunderburk — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-core?_sp.spa=pr-viewkeeper-modern-shadow](https://developer.blackbaud.com/skyux-core?_sp.spa=pr-viewkeeper-modern-shadow)

**Pull request merged**
